### ISSUE TITLE
Test implementation tracker

### ISSUE THREAD

**Issue by jfldde** [chainwayxyz/citrea-e2e#4]
- [ ] bitcoin reorgs 4 blocks
- [ ] bitcoin does not produces new blocks for 2 hours (Can mock by not calling generate for N amount of time)
- [ ] bitcoin produces 4 blocks really fast (Using `setmocktime`)
- [ ] bitcoin produces 2 blocks with incorrect timestamps (Using `setmocktime`)
- [x] Create da blocks while sequencer is looking for nonce and make sure sequencer process new da block in parallel (Regression fixed in https://github.com/chainwayxyz/citrea/pull/1311)
